In [1]:
import pandas as pd #data analysis library
import matplotlib.pyplot as plt #graphing
import seaborn as sns #graphing
import sklearn
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report

print("For this assignment we used the Abalone data set from the UCI Machine Learning Repository.\nhttps://archive.ics.uci.edu/ml/datasets/Abalone")
print("Our data set contains 9 features consisting of 8 quantitative features and 1 categorical feature (sex)")
df = pd.read_csv("Abalone.csv") #read in data
df.head()

For this assignment we used the Abalone data set from the UCI Machine Learning Repository.
https://archive.ics.uci.edu/ml/datasets/Abalone
Our data set contains 9 features consisting of 8 quantitative features and 1 categorical feature (sex)


Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [2]:
#preprocessing
print("We note that the sex column contains a third (intersex) class, so we eliminate rows of that class.")
df = df[df.Sex != 'I']
df.head()

We note that the sex column contains a third (intersex) class, so we eliminate rows of that class.


Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
6   F   0.530     0.415   0.150        0.7775          0.2370          0.1415   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
6         0.330     20

In [3]:
#set independent and dependent variables
x = df.iloc[:,1:9] #all entries from column 1 to 3
leng = df.iloc[:,1]
dim = df.iloc[:,2]
rin = df.iloc[:,3]
print(x)


      Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0      0.455     0.365   0.095        0.5140          0.2245          0.1010   
1      0.350     0.265   0.090        0.2255          0.0995          0.0485   
2      0.530     0.420   0.135        0.6770          0.2565          0.1415   
3      0.440     0.365   0.125        0.5160          0.2155          0.1140   
6      0.530     0.415   0.150        0.7775          0.2370          0.1415   
...      ...       ...     ...           ...             ...             ...   
4172   0.565     0.450   0.165        0.8870          0.3700          0.2390   
4173   0.590     0.440   0.135        0.9660          0.4390          0.2145   
4174   0.600     0.475   0.205        1.1760          0.5255          0.2875   
4175   0.625     0.485   0.150        1.0945          0.5310          0.2610   
4176   0.710     0.555   0.195        1.9485          0.9455          0.3765   

      Shell weight  Rings  
0          

In [4]:
y = df.iloc[:,0]
print(y)

0       M
1       M
2       F
3       M
6       F
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: Sex, Length: 2835, dtype: object


In [5]:
#train test split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0) #20% testing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train) 
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)  # apply same transformation to test data

In [6]:

clf = SGDClassifier(loss="log", penalty="l1", max_iter=100, alpha = .01, tol = .0001)
clf.fit(x_train, y_train)
SGDClassifier(max_iter=100000)

SGDClassifier(max_iter=100000)

In [7]:
clf.predict(x_test)

array(['F', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'F',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M',
       'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M',
       'F', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'F', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F', 'M',
       'M', 'M', 'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'F',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'M',
       'M', 'M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'F', 'M',
       'F', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F',
       'M', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'F

In [8]:
score = clf.score(x_test, y_test)
print("Training score: ", score) 

Training score:  0.54673721340388


In [21]:
print(clf.coef_)
print("Intercept: ", clf.intercept_)
print("Iterations to Converge = ", clf.n_iter_)
print("Solution = w = ", 0.18529409, " - ", 0.30473596, "*x2 - ", 0.08525884,"*x3 + ", 0.1772645, "*x5" )

[[-2.72222598  0.          0.          0.          0.          0.
   0.          0.        ]]
Intercept:  [-1.18184858]
Iterations to Converge =  35
Solution = w =  0.18529409  -  0.30473596 *x2 -  0.08525884 *x3 +  0.1772645 *x5


In [16]:
ypred = clf.predict(x_train)

#confusion matrix
cm = sklearn.metrics.confusion_matrix(y_train, ypred)
tn, fp, fn, tp = cm.ravel()
print(cm) 

[[559 477]
 [584 648]]


In [17]:
print("Evaluation Metrics for Training Set: ")
cr = classification_report(y_train, ypred)
print(cr) 
print("Misclassification Rate = ", (fp + fn)/ (tp + tn + fp + fn))
print("Learning Rate = ", .01)

Evaluation Metrics for Training Set: 
              precision    recall  f1-score   support

           F       0.49      0.54      0.51      1036
           M       0.58      0.53      0.55      1232

    accuracy                           0.53      2268
   macro avg       0.53      0.53      0.53      2268
weighted avg       0.54      0.53      0.53      2268

Misclassification Rate =  0.4678130511463845
Learning Rate =  0.01


In [18]:
#confusion matrix
ypred = clf.predict(x_test)
cm = sklearn.metrics.confusion_matrix(y_test, ypred)
tn, fp, fn, tp = cm.ravel()
print(cm) 

print("Evaluation Metrics for Test Set: ")

cr = classification_report(y_test, ypred)
print(cr) 
print("Misclassification Rate = ", (fp + fn)/ (tp + tn + fp + fn))
print("Learning Rate = ", .01)

[[133 138]
 [150 146]]
Evaluation Metrics for Test Set: 
              precision    recall  f1-score   support

           F       0.47      0.49      0.48       271
           M       0.51      0.49      0.50       296

    accuracy                           0.49       567
   macro avg       0.49      0.49      0.49       567
weighted avg       0.49      0.49      0.49       567

Misclassification Rate =  0.5079365079365079
Learning Rate =  0.01


In [19]:
#Iterations with varying Learning Rates / Tolerances


In [20]:
clf = SGDClassifier(loss="log", penalty="l1", max_iter=100000, alpha = .00001, tol = .001)
clf.fit(x_train, y_train)

SGDClassifier(max_iter=100000)

clf.predict(x_test)
score = clf.score(x_test, y_test)
print("Training score: ", score) 
print("Coefficients: ", clf.coef_)
print("Intercepts: ", clf.intercept_)
print("Iterations to Converge = ", clf.n_iter_)
print("Learning Rate = ", .01)

print("\nTraining Set:")
#training set
ypred = clf.predict(x_train)
#confusion matrix
cm = sklearn.metrics.confusion_matrix(y_train, ypred)
tn, fp, fn, tp = cm.ravel()
print("Confusion Matrix:")
print(cm)


print("Evaluation Metrics for Training Set: ")
cr = classification_report(y_train, ypred)
print(cr) 
print("Misclassification Rate = ", (fp + fn)/ (tp + tn + fp + fn))


#test set
#confusion matrix
print("\nTest Set:")
ypred = clf.predict(x_test)
cm = sklearn.metrics.confusion_matrix(y_test, ypred)
tn, fp, fn, tp = cm.ravel()
print("Confusion Matrix:")
print(cm) 

print("Evaluation Metrics for Test Set: ")

cr = classification_report(y_test, ypred)
print(cr) 
print("Misclassification Rate = ", (fp + fn)/ (tp + tn + fp + fn))

Training score:  0.5044091710758377
Coefficients:  [[-2.72222598  0.          0.          0.          0.          0.
   0.          0.        ]]
Intercepts:  [-1.18184858]
Iterations to Converge =  35
Learning Rate =  0.01

Training Set:
Confusion Matrix:
[[767 269]
 [845 387]]
Evaluation Metrics for Training Set: 
              precision    recall  f1-score   support

           F       0.48      0.74      0.58      1036
           M       0.59      0.31      0.41      1232

    accuracy                           0.51      2268
   macro avg       0.53      0.53      0.49      2268
weighted avg       0.54      0.51      0.49      2268

Misclassification Rate =  0.4911816578483245

Test Set:
Confusion Matrix:
[[197  74]
 [207  89]]
Evaluation Metrics for Test Set: 
              precision    recall  f1-score   support

           F       0.49      0.73      0.58       271
           M       0.55      0.30      0.39       296

    accuracy                           0.50       567
   macr

In [15]:
#Findings: making the alpha larger caused the program to converge quicker
#Making the tolerance smaller seemd to improve accuracy but making it too small would cause it to never converge